### ISSUE TITLE
Can I not share my source for a launcher I made based on this?

### ISSUE THREAD

**Issue by kyteidev** [kuzeeeyk/flexberry-launcher#5]
I made a launcher based on this one for my PvP client, but I don’t really want to share the source code because it contains some API tokens and database credentials. The GPL license states that I have to make my source code publicly available. I will give credits though

**Comment by kuzeeeyk** [comment]
You don't have to share source code as long as you give credits, thank you for asking me before publishing.
Also users can still access your API tokens etc. by unpacking .asar located in launcher, be cautious.

**Comment by kyteidev** [comment]
Ok, thanks for letting me know :)

**Comment by kuzeeeyk** [comment]
You're welcome. Feel free to ask any other questions about launcher :)
